apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mongodb-creds
  namespace: blog-app
spec:
  encryptedData:
    MONGO_INITDB_ROOT_PASSWORD: AgBZbdY/pz9Ne/z8AvipkJ66L/233YmCdHiB9dezfeLAtQQ/nPKPxlLgwrdPViTqznpZ19vZnQgENTdlyM3FTyy+vCFSmMrLSwjrfkKi+W+G1dLu0mgjGJTM6ZukKJpfs7gCIz451Fv8oAbkea2qT51QbxtH08jzzGi0nJ3+60F2oK+NWV+6+5f8VBgQ162SvT0nVQmctd2146weUJLZxlKiMCgSmXBzKQcXUc+/efXANnwa3i08q8FBN9Akd5PCTUPyEG6wUw56Fz6jOWRmJZX4TLtXzjrkrxiV2k9IN4MdapRMtKeC5sTEsG6oEuVSZahZvsuwM3z3hriOh5JoaMZfp9lFODRVO5GRuhj4c7s2K+J9TET/x4Oh0ZIhhH4fFR4FpeGfGlEuOKu7n2nBznF7JsXLDsqG0Mj4MrCKQURx+Z3wAAzsTRa9A5aSnNhONn8oE/yRKvokghJgGSy3+1Lru3YtNoMEyv3V1OrAnXuR3PDCWsuiRERXPeGs+oVTJYJLcs6ozWYHTnkbt7ShhfkQKip2PMtAce1HEFG8ZOMCNL/8fhlkPU7Gz4y9i2X0heT678UmMGeL5AXSEws3nu6i5s0gBzj0zUGDpxQV8irkHFvlHlvIk5431046qOItQBmDUiORUMMABDCK5eLaKgdUGeVjQF2ZBOYyU3mRde/B1tjzDuMPFXe2gni5ReB9XPQvqDg13EoTdg==
    MONGO_INITDB_ROOT_USERNAME: AgBzMLHH/BDSBT0gRz5hWk11hcDWYo1ycnqXXaBfJTT6qwhl3O4BdE6aB7Z6D5MmFOJAdlP56a6SSdWEsce2m6Xe5RmRjoCUB1e7WS4PwUq/mud/A7G2DAtHNBlgyD8VPsnid27ZQekXsp6GHksxxaL5Nf81GwbfE5wMF5j8NoLy9ckhdCeNlvdS4iZg2F6OhF6NsCuLFg2HEuCKUwj1ZGTFdBrdfynEyEwIbR6W0rQ7TF7EynWEA+cff5gFRhMNpAXgfyFkufV7X/wZfXD3/rsGdFTM2itPiHHPPxLMYICz5FJYE5itA+Y106mWOFQ1mfRZZPnAWUcj+8aJI1Kd8vhvhe/7Ii4IdgXhjpxgWmh5UIPhd6dfjtEv5lmUd+5asMchpNAyk85ReRUcmVs5XGK3qF2ICLshYnZGpKv2i/W48YT+MaGZY94Rg821aMOBmJ+d/tuXvxXKJBOTQ9Noh3vKwoIVi59gYUJqBiN32/+dspSCaurscCfUsXV8jrxNHWAAlbBxsCa9b+2eoGBr5LRmYPtwrrs74mIF/aPfd4BIT8WHnasp7gjoPgyTVRoj+bsHZSB9uu6rlCpag9Q68H6+9RNGxNg560vqYTeWZHUavyBwkRrpxrwkBaTmVuUhv2QdiwwwodXfpxBgdfY+whrj92MI3onmqaMi5w53igapFORwhnPObqZUVvrMVoK9dIWtzZnn
  template:
    metadata:
      creationTimestamp: null
      name: mongodb-creds
      namespace: blog-app

