name: Create Kubernetes Cluster
on: push
jobs:
  deploy-terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform
    steps:
    - uses: actions/checkout@v2
    - name: setup-terraform
      id: install-terraform
      run: wget -O terraform.zip https://releases.hashicorp.com/terraform/1.5.5/terraform_1.5.5_linux_amd64.zip && unzip terraform.zip && chmod +x terraform && sudo mv terraform /usr/local/bin

    - name: Terraform Init
      run: terraform init -backend-config="Duc-RG1" -backend-config="storage_account_name=ducleterraformbackend" -backend-config="container_name=terraform-backend" -backend-config="key=terraform.tfstate" -backend-config="access_key=${{ secrets.Access_Key }}"

    # Generates an execution plan for Terraform
    - name: Terraform Plan
      run: terraform plan -input=false

    - name: Terraform Apply
      run: terraform workspace select ${GITHUB_REF##*/} || terraform workspace new ${GITHUB_REF##*/} && terraform apply -auto-approve -var="branch=${GITHUB_REF##*/}"
